"""ride table

Revision ID: 665ec04707bf
Revises: 7dee1be5958b
Create Date: 2022-01-09 18:52:13.808606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665ec04707bf'
down_revision = '7dee1be5958b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_end_time'), 'ride', ['end_time'], unique=False)
    op.create_index(op.f('ix_ride_start_time'), 'ride', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ride_start_time'), table_name='ride')
    op.drop_index(op.f('ix_ride_end_time'), table_name='ride')
    op.drop_table('ride')
    op.drop_table('board')
    # ### end Alembic commands ###
