"""empty message

Revision ID: 6b829b7975cc
Revises: 665ec04707bf
Create Date: 2022-01-10 16:25:37.936072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b829b7975cc'
down_revision = '665ec04707bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=20), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    # ### end Alembic commands ###
