"""empty message

Revision ID: 6c3f4289fc9d
Revises: 30a862a46d8f
Create Date: 2022-06-18 09:42:02.007527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3f4289fc9d'
down_revision = '30a862a46d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('ride', sa.Column('beach_name', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'beach_name')
    op.drop_column('ride', 'cost')
    # ### end Alembic commands ###
